package com.bank.bian.savingsaccount;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Savings Account
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Account Management
 * Functional Pattern: Fulfill
 * Asset Type:         Savings Account Facility
 * Control Record:     Savings Account Facility Fulfillment Arrangement
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Savings Account — BIAN Semantic API")
                .description("Service Domain 'Savings Account' (Fulfill pattern) "
                        + "operating on the 'Savings Account Facility Fulfillment Arrangement' control record.")
                .version("0.1.0"));
    }
}
